# Generated by Django 2.2.12 on 2022-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_generalnotification_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnotification',
            name='status',
            field=models.CharField(default='Unvisited', max_length=100),
        ),
    ]
